### ISSUE TITLE
Executing Task::async immediately

### ISSUE THREAD

**Issue by kelunik** [concurrent-php/ext-async#52] opened 2018-07-26 20:17 UTC
Executing `Task::async` in a `defer` watcher causes several problems making code harder to write, e.g.

```
Task::async([$this, 'write'], "foo");
$this->write("bar");
```

will first write `"foo"` then `"bar"`. Another example:

```
/** @inheritdoc */
public function end(string $data = ""): Promise
{
    // TODO: Set writable directly to false here
    $this->write($data);
    $this->writable = false;
    $this->close();
}
```

**Comment by martinschroeder** [comment] 2018-07-30 16:48
I don't get why the order of output in your first example should be `"foo"` first, this is really not intended behavior...

**Comment by kelunik** [comment] 2018-07-30 20:10
Executing `async` immediately until the first `await` would solve a few problems that are not that easy to solve otherwise. It's not your intention, but I'd like that. Maybe @trowski has an additional opinion on that.

`async` basically doesn't mean _do something later_ for me, but rather _don't block here_.

**Comment by kelunik** [comment] 2018-08-01 17:08
> As far as the order of execution is concerned there have been debates about when promises should be resolved

I'm well aware. Promise resolution is a similar but slightly different topic than calling `Task::async`.

> having to do fiber context switches as they are created

While performance is one concern, it's not the one the decision should be based on for this case IMO. Context switches aren't _that_ expensive.

> If you rely on the order of execution of multiple independent tasks without explicit synchronization this is IMO a mistake that leads to problems.

It's usually not a problem, especially not for class-internal calls like a method setting a flag at the start of the method before it ever blocks.

Both options are valid options. They both have their advantages and disadvantages. Talking about performance, [always async increases latency](https://github.com/async-interop/promise/issues/20#issuecomment-261289083). In https://github.com/async-interop/promise/pull/26 we agreed on always-sync invocations.

If you don't agree, please leave this issue open for further discussion once we're moving the discussion to internals @ php-src.

**Comment by martinschroeder** [comment] 2018-08-02 07:53
@trowski With the current version (0.1.0) the task will be executed in a defer watcher if `Deferred::resolve()` is called from a watcher registered with your event loop. Things are different when `Deferred::resolve()` is called from within a running task, in that case there will be no defer watcher as tasks are resumed in a dispatch loop without delay.

I am moving on with PR #57 that integrates libuv with the async extension bumping it to version `0.2`. I branched the current master into `0.1.x` so you can use that in amp to keep using your own event loop. Version `0.2` will drop support for custom task schedulers as it provides a builtin event loop instead.

**Comment by trowski** [comment] 2018-08-07 17:10
I think the behavior of `Deferred::resolve()` should be consistent, either always async or always sync. Always async is nice in that programmers don't have to worry about state when calling resolve, but introduces latency that's unnecessary, so I'd probably prefer always sync.

We'll migrate Amp to using `0.2`.

**Comment by martinschroeder** [comment] 2018-08-08 12:30
@trowski I prefer always async because it is more convenient to work with. One thing that can be done to mitigate any latency issues with this approach is to push tasks that are being resumed to the front of the scheduler's ready queue instead of pushing them to the back. This would ensure that the most-recent resume operation will always be the next operation performed by the scheduler. It will be almost as fast as the always sync approach since every task in the ready queue is dispatched / resumed by the dispatcher loop in an idle watcher (libuv). There will be no timers or IO / signals between triggering a continuation and executing it. In essence we get always async with (almost) no additional latency.

> We'll migrate Amp to using 0.2.

I will close all issues marked as `0.1.x` for now because i do not have enough time to work on more than a single branch. It is unlikely that the exact same issues will occur with `0.2.x` which would require opening new issues as they happen.

**Comment by kelunik** [comment] 2018-08-08 12:35
@martinschroeder That seems like a bad idea, it will result in some tasks completely stalling, because there are always new tasks inserted at the front, no?

**Comment by martinschroeder** [comment] 2018-08-08 12:40
@kelunik This would be the case if your tasks never stop to wait for IO or timers (which should never happen unless there is something very wrong about the tasks). You do have the same problem with always sync since it would busy-loop between a few tasks.

**Comment by kelunik** [comment] 2018-08-08 14:42
@martinschroeder It shouldn't do that forever, of course. But scheduling to the start of the queue only reduces fairness, but doesn't improve overall latency, if I'm not mistaken.

**Comment by martinschroeder** [comment] 2018-10-08 08:35
I added the `revisit` label and will be closing this for now. It can be revisited sometime when the extension is more mature.

**Closed by martinschroeder** 2018-10-08 08:35 UTC
Labels: revisit topic

**Comment by martinschroeder** [comment] 2018-12-24 09:34
@kelunik @trowski With recent changes to `master` and PR #87 `ext-async` uses an (almost) always sync execution model. All continuations will be called immediately as operations complete. The only exception to that rule is starting new tasks using `Task::async()`, starting these tasks is deferred to the next tick of the event loop to increase the chance to inline new tasks whenever it is possible.
